<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN2bEhdR\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN2bEhdR/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerN2bEhdR.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerN2bEhdR\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerN2bEhdR\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'N2bEhdR',
    'container.build_id' => '65b682be',
    'container.build_time' => 1529484473,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerN2bEhdR');
